// ---------------------------------------------------------------------------
// bands.cjs -- raster band tables for the perspective ground plane.
//
//   sky bands   recolour palette entry 0 to paint the sky gradient
//   ground band VSCROLL(y) = camV + PC/d - y, sampling the tilemap deeper the
//               closer the row is to the horizon
//
// PC/DMIN must stay under 1024 (the tilemap is 64 tiles of 16px tall) or the
// far distance wraps back on itself.
// ---------------------------------------------------------------------------
'use strict';
const fs = require('fs');
const path = require('path');

const HOR = 76;          // logical row of the horizon
const BOT = 240;
const DMIN = 8;
const PC = 4150;         // perspective constant
const NSKY = 10;         // sky gradient steps
const NGROUND = 38;

// --- sky: deep blue at the top fading to haze at the horizon ---------------
const SKY_TOP = [0x4f, 0x92, 0xcf];
const SKY_HOR = [0xd5, 0xe3, 0xee];
const skyline = [], skycol = [];
for (let i = 0; i < NSKY; i++) {
  const y = Math.round((HOR * i) / NSKY);
  skyline.push(y * 2);                                  // physical scanline
  const t = i / (NSKY - 1);
  const c = SKY_TOP.map((v, k) => Math.round(v + (SKY_HOR[k] - v) * t));
  const [r, g, b] = c.map((v) => v >> 4);
  skycol.push([(g << 4) | b, r]);                       // VERA 12-bit entry
}

// --- ground bands ----------------------------------------------------------
const gline = [], vs = [];
for (let i = 0; i < NGROUND; i++) {
  const y = HOR + Math.round(((BOT - HOR) * i) / NGROUND);
  gline.push(y * 2);
  const d = Math.max(DMIN, y - HOR + DMIN);
  vs.push(Math.round(PC / d - y) & 4095);
}

// --- object projection: world depth -> screen row ---------------------------
// index = zrel >> 2, so zrel = i*4 and row = HOR - DMIN + PC/zrel
const rowtab = [];
for (let i = 0; i < 256; i++) {
  const zrel = i * 4;
  const row = zrel === 0 ? 999 : HOR - DMIN + PC / zrel;
  rowtab.push(Math.max(0, Math.min(255, Math.round(row))));
}

const line = [...skyline, ...gline];
const row = (n, a, f) => `${n}:\n` + (() => {
  let s = '';
  for (let i = 0; i < a.length; i += 16) s += '        .byte ' + a.slice(i, i + 16).map(f).join(',') + '\n';
  return s;
})();

let s = '; Generated by tools/bands.cjs -- do not edit.\n\n';
s += `HORIZON = ${HOR}\nDMIN    = ${DMIN}\nPERSP   = ${PC}\n`;
s += `NSKY    = ${NSKY}\nNGROUND = ${NGROUND}\nNBANDS  = ${NSKY + NGROUND}\n\n`;
s += `skyline_l = bandline_l\n\n`;
s += row('bandline_l', line, (v) => v & 255);
s += row('bandline_h', line, (v) => v >> 8);
s += row('skycol_l', skycol, (v) => '$' + v[0].toString(16).padStart(2, '0'));
s += row('skycol_h', skycol, (v) => '$' + v[1].toString(16).padStart(2, '0'));
s += row('bandvs_l', vs, (v) => v & 255);
s += row('bandvs_h', vs, (v) => v >> 8);
s += row('rowtab', rowtab, (v) => v);

fs.writeFileSync(path.join(__dirname, '..', 'src', 'data', 'bands.inc'), s);
console.log(`horizon row ${HOR}, ${NSKY} sky + ${NGROUND} ground bands`);
console.log(`visible depth ${Math.round(PC / (BOT - HOR + DMIN))}..${Math.round(PC / DMIN)} world px`);
